# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DBIx-TextIndex
version:      0.24
version_from: lib/DBIx/TextIndex.pm
installdirs:  site
requires:
    Bit::Vector:                   6.3
    DBI:                           1.43
    Exception::Class:              1.12
    HTML::Entities:                1.22
    Text::Balanced:                1.83

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
